#!/bin/bash

function echo_green {
    if [[ $silent -eq 0 ]]; then
        echo -e "\033[32m$* \033[0m"
    fi
}

function echo_red {
    if [[ $silent -eq 0 ]]; then
        echo -e "\033[31m$* \033[0m"
    fi
}
function echo_yellow {
    if [[ $silent -eq 0 ]]; then
        echo -e "\033[33m$* \033[0m"
    fi
}

function delete_if_exist {
    if [[ -d $1 || -f $1 ]];then
        rm -rf $1
    fi
}

jump_ip_str=zeekr@10.138.22.46
target_ip_str=root@10.204.0.1

if [[ $# -ne 2 && $# -ne 3 ]]; then
    echo "usage: send_s32g [-r]  /source/file/path /remote/target/file/path"
    exit
fi
if [[ $# == 2 ]];then
    param=""
    file=$1
    target_file=$2
else
    param=$1
    file=$2
    target_file=$3
fi

# echo "param: [$param], file:[$file], target_file:[$target_file]"

filename=`echo $file | awk -F\/ '{print $NF}'`
# 1. 删除跳板机上的旧文件，如果存在的话
output=`my_ssh $jump_ip_str "if [[ -d /tmp/$file ]];then rm -rf /tmp/$file;fi"`
output=`my_ssh $jump_ip_str "if [[ -f /tmp/$file ]];then rm -rf /tmp/$file;fi"`
echo_yellow "<<<< scp $filename to $target_file"
# 2. scp 到跳板机
# 3. 从跳板机scp到s32g
output=`my_scp $param $file $jump_ip_str:/tmp/;my_ssh $jump_ip_str "ssh $target_ip_str '$(declare -f delete_if_exist);delete_if_exist $target_file/$filename';scp $param /tmp/$filename $target_ip_str:$target_file"`
echo_yellow ">>>> scp $filename to $target_file end"

function get_md5() {
    target_ip_str=root@10.204.0.1
    ssh $target_ip_str "md5sum $1"
}

# 4. 检查scp到s32g的文件与本地文件的md5值是否一直
if [[ -f $file ]];then
    echo_yellow "checking md5 ..."
    md5_output=`md5sum $file`
    remote_md5_output=`my_ssh zeekr@10.138.22.46 "$(declare -f get_md5); get_md5 $target_file/$filename"`
    remote_md5_output=`echo $remote_md5_output | sed 's/[^[:print:]]//g' | awk -F "password:" '{print $2}'`
    md5=`echo $md5_output | awk '{print $1}'`
    remote_md5=`echo $remote_md5_output | awk '{print $1}'`
    # echo "md5: $md5, remote_md5:$remote_md5"
    if [[ ! $md5 = "" &&  $md5 = $remote_md5 ]];then
        echo_green $md5_output
        echo_green $remote_md5_output
    else
        echo_red $md5_output
        echo_red $remote_md5_output
	echo $output
    fi
fi
